package entity;
// Generated 16-10-2016 1:46:00 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AliadosId generated by hbm2java
 */
@Embeddable
public class AliadosId  implements java.io.Serializable {


     private int productorProductorId;
     private int productorProductorId1;

    public AliadosId() {
    }

    public AliadosId(int productorProductorId, int productorProductorId1) {
       this.productorProductorId = productorProductorId;
       this.productorProductorId1 = productorProductorId1;
    }
   


    @Column(name="PRODUCTOR_PRODUCTOR_ID", nullable=false, precision=8, scale=0)
    public int getProductorProductorId() {
        return this.productorProductorId;
    }
    
    public void setProductorProductorId(int productorProductorId) {
        this.productorProductorId = productorProductorId;
    }


    @Column(name="PRODUCTOR_PRODUCTOR_ID1", nullable=false, precision=8, scale=0)
    public int getProductorProductorId1() {
        return this.productorProductorId1;
    }
    
    public void setProductorProductorId1(int productorProductorId1) {
        this.productorProductorId1 = productorProductorId1;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AliadosId) ) return false;
		 AliadosId castOther = ( AliadosId ) other; 
         
		 return (this.getProductorProductorId()==castOther.getProductorProductorId())
 && (this.getProductorProductorId1()==castOther.getProductorProductorId1());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProductorProductorId();
         result = 37 * result + this.getProductorProductorId1();
         return result;
   }   


}


