package entity;
// Generated 16-10-2016 1:46:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categorias generated by hbm2java
 */
@Entity
@Table(name="CATEGORIAS"
    ,schema="GRUPO03"
)
public class Categorias  implements java.io.Serializable {


     private int idCategoria;
     private String nombreCategoria;
     private Set<Productos> productoses = new HashSet<Productos>(0);

    public Categorias() {
    }

	
    public Categorias(int idCategoria, String nombreCategoria) {
        this.idCategoria = idCategoria;
        this.nombreCategoria = nombreCategoria;
    }
    public Categorias(int idCategoria, String nombreCategoria, Set<Productos> productoses) {
       this.idCategoria = idCategoria;
       this.nombreCategoria = nombreCategoria;
       this.productoses = productoses;
    }
   
     @Id 

    
    @Column(name="ID_CATEGORIA", unique=true, nullable=false, precision=5, scale=0)
    public int getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(int idCategoria) {
        this.idCategoria = idCategoria;
    }

    
    @Column(name="NOMBRE_CATEGORIA", nullable=false, length=120)
    public String getNombreCategoria() {
        return this.nombreCategoria;
    }
    
    public void setNombreCategoria(String nombreCategoria) {
        this.nombreCategoria = nombreCategoria;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categorias")
    public Set<Productos> getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set<Productos> productoses) {
        this.productoses = productoses;
    }




}


