package entity;
// Generated 16-10-2016 1:46:00 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Compradores generated by hbm2java
 */
@Entity
@Table(name="COMPRADORES"
    ,schema="GRUPO03"
    , uniqueConstraints = @UniqueConstraint(columnNames="USUARIO_RUT") 
)
public class Compradores  implements java.io.Serializable {


     private BigDecimal idComprador;
     private Usuarios usuarios;
     private Set<Compras> comprases = new HashSet<Compras>(0);

    public Compradores() {
    }

	
    public Compradores(BigDecimal idComprador, Usuarios usuarios) {
        this.idComprador = idComprador;
        this.usuarios = usuarios;
    }
    public Compradores(BigDecimal idComprador, Usuarios usuarios, Set<Compras> comprases) {
       this.idComprador = idComprador;
       this.usuarios = usuarios;
       this.comprases = comprases;
    }
   
     @Id 

    
    @Column(name="ID_COMPRADOR", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getIdComprador() {
        return this.idComprador;
    }
    
    public void setIdComprador(BigDecimal idComprador) {
        this.idComprador = idComprador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USUARIO_RUT", unique=true, nullable=false)
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="compradores")
    public Set<Compras> getComprases() {
        return this.comprases;
    }
    
    public void setComprases(Set<Compras> comprases) {
        this.comprases = comprases;
    }




}


