package entity;
// Generated 16-10-2016 1:46:00 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetallescomprasId generated by hbm2java
 */
@Embeddable
public class DetallescomprasId  implements java.io.Serializable {


     private long ofertaIdOferta;
     private long compraIdCompra;

    public DetallescomprasId() {
    }

    public DetallescomprasId(long ofertaIdOferta, long compraIdCompra) {
       this.ofertaIdOferta = ofertaIdOferta;
       this.compraIdCompra = compraIdCompra;
    }
   


    @Column(name="OFERTA_ID_OFERTA", nullable=false, precision=12, scale=0)
    public long getOfertaIdOferta() {
        return this.ofertaIdOferta;
    }
    
    public void setOfertaIdOferta(long ofertaIdOferta) {
        this.ofertaIdOferta = ofertaIdOferta;
    }


    @Column(name="COMPRA_ID_COMPRA", nullable=false, precision=12, scale=0)
    public long getCompraIdCompra() {
        return this.compraIdCompra;
    }
    
    public void setCompraIdCompra(long compraIdCompra) {
        this.compraIdCompra = compraIdCompra;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetallescomprasId) ) return false;
		 DetallescomprasId castOther = ( DetallescomprasId ) other; 
         
		 return (this.getOfertaIdOferta()==castOther.getOfertaIdOferta())
 && (this.getCompraIdCompra()==castOther.getCompraIdCompra());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getOfertaIdOferta();
         result = 37 * result + (int) this.getCompraIdCompra();
         return result;
   }   


}


