package entity;
// Generated 16-10-2016 1:46:00 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detallescompras generated by hbm2java
 */
@Entity
@Table(name="DETALLESCOMPRAS"
    ,schema="GRUPO03"
)
public class Detallescompras  implements java.io.Serializable {


     private DetallescomprasId id;
     private Compras compras;
     private Ofertas ofertas;
     private int totalDetallecompra;
     private int cantidadDetallecompra;

    public Detallescompras() {
    }

    public Detallescompras(DetallescomprasId id, Compras compras, Ofertas ofertas, int totalDetallecompra, int cantidadDetallecompra) {
       this.id = id;
       this.compras = compras;
       this.ofertas = ofertas;
       this.totalDetallecompra = totalDetallecompra;
       this.cantidadDetallecompra = cantidadDetallecompra;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="ofertaIdOferta", column=@Column(name="OFERTA_ID_OFERTA", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="compraIdCompra", column=@Column(name="COMPRA_ID_COMPRA", nullable=false, precision=12, scale=0) ) } )
    public DetallescomprasId getId() {
        return this.id;
    }
    
    public void setId(DetallescomprasId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COMPRA_ID_COMPRA", nullable=false, insertable=false, updatable=false)
    public Compras getCompras() {
        return this.compras;
    }
    
    public void setCompras(Compras compras) {
        this.compras = compras;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="OFERTA_ID_OFERTA", nullable=false, insertable=false, updatable=false)
    public Ofertas getOfertas() {
        return this.ofertas;
    }
    
    public void setOfertas(Ofertas ofertas) {
        this.ofertas = ofertas;
    }

    
    @Column(name="TOTAL_DETALLECOMPRA", nullable=false, precision=9, scale=0)
    public int getTotalDetallecompra() {
        return this.totalDetallecompra;
    }
    
    public void setTotalDetallecompra(int totalDetallecompra) {
        this.totalDetallecompra = totalDetallecompra;
    }

    
    @Column(name="CANTIDAD_DETALLECOMPRA", nullable=false, precision=9, scale=0)
    public int getCantidadDetallecompra() {
        return this.cantidadDetallecompra;
    }
    
    public void setCantidadDetallecompra(int cantidadDetallecompra) {
        this.cantidadDetallecompra = cantidadDetallecompra;
    }




}


