package entity;
// Generated 16-10-2016 1:46:00 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detallesventas generated by hbm2java
 */
@Entity
@Table(name="DETALLESVENTAS"
    ,schema="GRUPO03"
)
public class Detallesventas  implements java.io.Serializable {


     private DetallesventasId id;
     private Ofertas ofertas;
     private Ventas ventas;
     private long totalDetalleventa;
     private long cantidadDetalleventa;

    public Detallesventas() {
    }

    public Detallesventas(DetallesventasId id, Ofertas ofertas, Ventas ventas, long totalDetalleventa, long cantidadDetalleventa) {
       this.id = id;
       this.ofertas = ofertas;
       this.ventas = ventas;
       this.totalDetalleventa = totalDetalleventa;
       this.cantidadDetalleventa = cantidadDetalleventa;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="ofertaIdOferta", column=@Column(name="OFERTA_ID_OFERTA", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="ventaIdVenta", column=@Column(name="VENTA_ID_VENTA", nullable=false, precision=10, scale=0) ) } )
    public DetallesventasId getId() {
        return this.id;
    }
    
    public void setId(DetallesventasId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="OFERTA_ID_OFERTA", nullable=false, insertable=false, updatable=false)
    public Ofertas getOfertas() {
        return this.ofertas;
    }
    
    public void setOfertas(Ofertas ofertas) {
        this.ofertas = ofertas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="VENTA_ID_VENTA", nullable=false, insertable=false, updatable=false)
    public Ventas getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Ventas ventas) {
        this.ventas = ventas;
    }

    
    @Column(name="TOTAL_DETALLEVENTA", nullable=false, precision=10, scale=0)
    public long getTotalDetalleventa() {
        return this.totalDetalleventa;
    }
    
    public void setTotalDetalleventa(long totalDetalleventa) {
        this.totalDetalleventa = totalDetalleventa;
    }

    
    @Column(name="CANTIDAD_DETALLEVENTA", nullable=false, precision=10, scale=0)
    public long getCantidadDetalleventa() {
        return this.cantidadDetalleventa;
    }
    
    public void setCantidadDetalleventa(long cantidadDetalleventa) {
        this.cantidadDetalleventa = cantidadDetalleventa;
    }




}


