package entity;
// Generated 16-10-2016 1:46:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ofertas generated by hbm2java
 */
@Entity
@Table(name="OFERTAS"
    ,schema="GRUPO03"
)
public class Ofertas  implements java.io.Serializable {


     private long idOferta;
     private Productos productos;
     private Productores productores;
     private Date fechaCreacionOferta;
     private String vigenciaOferta;
     private long costoUnidad;
     private long stockOferta;
     private String repartoOferta;
     private String zonaOrigen;
     private String descripcionOferta;
     private Set<Detallescompras> detallescomprases = new HashSet<Detallescompras>(0);
     private Set<Detallesventas> detallesventases = new HashSet<Detallesventas>(0);

    public Ofertas() {
    }

	
    public Ofertas(long idOferta, Productos productos, Date fechaCreacionOferta, String vigenciaOferta, long costoUnidad, long stockOferta, String repartoOferta, String zonaOrigen) {
        this.idOferta = idOferta;
        this.productos = productos;
        this.fechaCreacionOferta = fechaCreacionOferta;
        this.vigenciaOferta = vigenciaOferta;
        this.costoUnidad = costoUnidad;
        this.stockOferta = stockOferta;
        this.repartoOferta = repartoOferta;
        this.zonaOrigen = zonaOrigen;
    }
    public Ofertas(long idOferta, Productos productos, Productores productores, Date fechaCreacionOferta, String vigenciaOferta, long costoUnidad, long stockOferta, String repartoOferta, String zonaOrigen, String descripcionOferta, Set<Detallescompras> detallescomprases, Set<Detallesventas> detallesventases) {
       this.idOferta = idOferta;
       this.productos = productos;
       this.productores = productores;
       this.fechaCreacionOferta = fechaCreacionOferta;
       this.vigenciaOferta = vigenciaOferta;
       this.costoUnidad = costoUnidad;
       this.stockOferta = stockOferta;
       this.repartoOferta = repartoOferta;
       this.zonaOrigen = zonaOrigen;
       this.descripcionOferta = descripcionOferta;
       this.detallescomprases = detallescomprases;
       this.detallesventases = detallesventases;
    }
   
     @Id 

    
    @Column(name="ID_OFERTA", unique=true, nullable=false, precision=12, scale=0)
    public long getIdOferta() {
        return this.idOferta;
    }
    
    public void setIdOferta(long idOferta) {
        this.idOferta = idOferta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRODUCTO_ID_PRODUCTO", nullable=false)
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRODUCTOR_PRODUCTOR_ID")
    public Productores getProductores() {
        return this.productores;
    }
    
    public void setProductores(Productores productores) {
        this.productores = productores;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_CREACION_OFERTA", nullable=false, length=7)
    public Date getFechaCreacionOferta() {
        return this.fechaCreacionOferta;
    }
    
    public void setFechaCreacionOferta(Date fechaCreacionOferta) {
        this.fechaCreacionOferta = fechaCreacionOferta;
    }

    
    @Column(name="VIGENCIA_OFERTA", nullable=false, length=4)
    public String getVigenciaOferta() {
        return this.vigenciaOferta;
    }
    
    public void setVigenciaOferta(String vigenciaOferta) {
        this.vigenciaOferta = vigenciaOferta;
    }

    
    @Column(name="COSTO_UNIDAD", nullable=false, precision=12, scale=0)
    public long getCostoUnidad() {
        return this.costoUnidad;
    }
    
    public void setCostoUnidad(long costoUnidad) {
        this.costoUnidad = costoUnidad;
    }

    
    @Column(name="STOCK_OFERTA", nullable=false, precision=12, scale=0)
    public long getStockOferta() {
        return this.stockOferta;
    }
    
    public void setStockOferta(long stockOferta) {
        this.stockOferta = stockOferta;
    }

    
    @Column(name="REPARTO_OFERTA", nullable=false, length=4)
    public String getRepartoOferta() {
        return this.repartoOferta;
    }
    
    public void setRepartoOferta(String repartoOferta) {
        this.repartoOferta = repartoOferta;
    }

    
    @Column(name="ZONA_ORIGEN", nullable=false, length=200)
    public String getZonaOrigen() {
        return this.zonaOrigen;
    }
    
    public void setZonaOrigen(String zonaOrigen) {
        this.zonaOrigen = zonaOrigen;
    }

    
    @Column(name="DESCRIPCION_OFERTA", length=1600)
    public String getDescripcionOferta() {
        return this.descripcionOferta;
    }
    
    public void setDescripcionOferta(String descripcionOferta) {
        this.descripcionOferta = descripcionOferta;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ofertas")
    public Set<Detallescompras> getDetallescomprases() {
        return this.detallescomprases;
    }
    
    public void setDetallescomprases(Set<Detallescompras> detallescomprases) {
        this.detallescomprases = detallescomprases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ofertas")
    public Set<Detallesventas> getDetallesventases() {
        return this.detallesventases;
    }
    
    public void setDetallesventases(Set<Detallesventas> detallesventases) {
        this.detallesventases = detallesventases;
    }




}


