package entity;
// Generated 16-10-2016 1:46:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Productos generated by hbm2java
 */
@Entity
@Table(name="PRODUCTOS"
    ,schema="GRUPO03"
)
public class Productos  implements java.io.Serializable {


     private int idProducto;
     private Categorias categorias;
     private Pesajes pesajes;
     private String nombreProducto;
     private String temporadaProducto;
     private String descripcionProducto;
     private Set<Ofertas> ofertases = new HashSet<Ofertas>(0);

    public Productos() {
    }

	
    public Productos(int idProducto, Categorias categorias, Pesajes pesajes, String nombreProducto, String temporadaProducto) {
        this.idProducto = idProducto;
        this.categorias = categorias;
        this.pesajes = pesajes;
        this.nombreProducto = nombreProducto;
        this.temporadaProducto = temporadaProducto;
    }
    public Productos(int idProducto, Categorias categorias, Pesajes pesajes, String nombreProducto, String temporadaProducto, String descripcionProducto, Set<Ofertas> ofertases) {
       this.idProducto = idProducto;
       this.categorias = categorias;
       this.pesajes = pesajes;
       this.nombreProducto = nombreProducto;
       this.temporadaProducto = temporadaProducto;
       this.descripcionProducto = descripcionProducto;
       this.ofertases = ofertases;
    }
   
     @Id 

    
    @Column(name="ID_PRODUCTO", unique=true, nullable=false, precision=9, scale=0)
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CATEGORIA_ID_CATEGORIA", nullable=false)
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PESAJE_ID_PESAJE", nullable=false)
    public Pesajes getPesajes() {
        return this.pesajes;
    }
    
    public void setPesajes(Pesajes pesajes) {
        this.pesajes = pesajes;
    }

    
    @Column(name="NOMBRE_PRODUCTO", nullable=false, length=400)
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }

    
    @Column(name="TEMPORADA_PRODUCTO", nullable=false, length=4)
    public String getTemporadaProducto() {
        return this.temporadaProducto;
    }
    
    public void setTemporadaProducto(String temporadaProducto) {
        this.temporadaProducto = temporadaProducto;
    }

    
    @Column(name="DESCRIPCION_PRODUCTO", length=300)
    public String getDescripcionProducto() {
        return this.descripcionProducto;
    }
    
    public void setDescripcionProducto(String descripcionProducto) {
        this.descripcionProducto = descripcionProducto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="productos")
    public Set<Ofertas> getOfertases() {
        return this.ofertases;
    }
    
    public void setOfertases(Set<Ofertas> ofertases) {
        this.ofertases = ofertases;
    }




}


