package entity;
// Generated 16-10-2016 1:46:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Productores generated by hbm2java
 */
@Entity
@Table(name="PRODUCTORES"
    ,schema="GRUPO03"
    , uniqueConstraints = @UniqueConstraint(columnNames="USUARIO_RUT") 
)
public class Productores  implements java.io.Serializable {


     private int productorId;
     private Usuarios usuarios;
     private String estado;
     private Set<Ofertas> ofertases = new HashSet<Ofertas>(0);
     private Set<Aliados> aliadosesForProductorProductorId = new HashSet<Aliados>(0);
     private Set<Aliados> aliadosesForProductorProductorId1 = new HashSet<Aliados>(0);
     private Set<Ventas> ventases = new HashSet<Ventas>(0);

    public Productores() {
    }

	
    public Productores(int productorId, Usuarios usuarios, String estado) {
        this.productorId = productorId;
        this.usuarios = usuarios;
        this.estado = estado;
    }
    public Productores(int productorId, Usuarios usuarios, String estado, Set<Ofertas> ofertases, Set<Aliados> aliadosesForProductorProductorId, Set<Aliados> aliadosesForProductorProductorId1, Set<Ventas> ventases) {
       this.productorId = productorId;
       this.usuarios = usuarios;
       this.estado = estado;
       this.ofertases = ofertases;
       this.aliadosesForProductorProductorId = aliadosesForProductorProductorId;
       this.aliadosesForProductorProductorId1 = aliadosesForProductorProductorId1;
       this.ventases = ventases;
    }
   
     @Id 

    
    @Column(name="PRODUCTOR_ID", unique=true, nullable=false, precision=8, scale=0)
    public int getProductorId() {
        return this.productorId;
    }
    
    public void setProductorId(int productorId) {
        this.productorId = productorId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USUARIO_RUT", unique=true, nullable=false)
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }

    
    @Column(name="ESTADO", nullable=false, length=80)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="productores")
    public Set<Ofertas> getOfertases() {
        return this.ofertases;
    }
    
    public void setOfertases(Set<Ofertas> ofertases) {
        this.ofertases = ofertases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="productoresByProductorProductorId")
    public Set<Aliados> getAliadosesForProductorProductorId() {
        return this.aliadosesForProductorProductorId;
    }
    
    public void setAliadosesForProductorProductorId(Set<Aliados> aliadosesForProductorProductorId) {
        this.aliadosesForProductorProductorId = aliadosesForProductorProductorId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="productoresByProductorProductorId1")
    public Set<Aliados> getAliadosesForProductorProductorId1() {
        return this.aliadosesForProductorProductorId1;
    }
    
    public void setAliadosesForProductorProductorId1(Set<Aliados> aliadosesForProductorProductorId1) {
        this.aliadosesForProductorProductorId1 = aliadosesForProductorProductorId1;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="productores")
    public Set<Ventas> getVentases() {
        return this.ventases;
    }
    
    public void setVentases(Set<Ventas> ventases) {
        this.ventases = ventases;
    }




}


