package entity;
// Generated 16-10-2016 1:46:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipocuenta generated by hbm2java
 */
@Entity
@Table(name="TIPOCUENTA"
    ,schema="GRUPO03"
)
public class Tipocuenta  implements java.io.Serializable {


     private boolean idTipocuenta;
     private String descripcionTipocuenta;
     private Set<Cuentas> cuentases = new HashSet<Cuentas>(0);

    public Tipocuenta() {
    }

	
    public Tipocuenta(boolean idTipocuenta, String descripcionTipocuenta) {
        this.idTipocuenta = idTipocuenta;
        this.descripcionTipocuenta = descripcionTipocuenta;
    }
    public Tipocuenta(boolean idTipocuenta, String descripcionTipocuenta, Set<Cuentas> cuentases) {
       this.idTipocuenta = idTipocuenta;
       this.descripcionTipocuenta = descripcionTipocuenta;
       this.cuentases = cuentases;
    }
   
     @Id 

    
    @Column(name="ID_TIPOCUENTA", unique=true, nullable=false, precision=1, scale=0)
    public boolean isIdTipocuenta() {
        return this.idTipocuenta;
    }
    
    public void setIdTipocuenta(boolean idTipocuenta) {
        this.idTipocuenta = idTipocuenta;
    }

    
    @Column(name="DESCRIPCION_TIPOCUENTA", nullable=false, length=60)
    public String getDescripcionTipocuenta() {
        return this.descripcionTipocuenta;
    }
    
    public void setDescripcionTipocuenta(String descripcionTipocuenta) {
        this.descripcionTipocuenta = descripcionTipocuenta;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipocuenta")
    public Set<Cuentas> getCuentases() {
        return this.cuentases;
    }
    
    public void setCuentases(Set<Cuentas> cuentases) {
        this.cuentases = cuentases;
    }




}


