package entity;
// Generated 16-10-2016 1:46:00 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Ubicaciones generated by hbm2java
 */
@Entity
@Table(name="UBICACIONES"
    ,schema="GRUPO03"
    , uniqueConstraints = @UniqueConstraint(columnNames="CUENTA_ID_CUENTA") 
)
public class Ubicaciones  implements java.io.Serializable {


     private long idUbicacion;
     private Cuentas cuentas;
     private String ciudad;
     private String calle;
     private long numero;
     private String codigoPostal;
     private String region;
     private long longitud;
     private long latitud;

    public Ubicaciones() {
    }

    public Ubicaciones(long idUbicacion, Cuentas cuentas, String ciudad, String calle, long numero, String codigoPostal, String region, long longitud, long latitud) {
       this.idUbicacion = idUbicacion;
       this.cuentas = cuentas;
       this.ciudad = ciudad;
       this.calle = calle;
       this.numero = numero;
       this.codigoPostal = codigoPostal;
       this.region = region;
       this.longitud = longitud;
       this.latitud = latitud;
    }
   
     @Id 

    
    @Column(name="ID_UBICACION", unique=true, nullable=false, precision=10, scale=0)
    public long getIdUbicacion() {
        return this.idUbicacion;
    }
    
    public void setIdUbicacion(long idUbicacion) {
        this.idUbicacion = idUbicacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CUENTA_ID_CUENTA", unique=true, nullable=false)
    public Cuentas getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Cuentas cuentas) {
        this.cuentas = cuentas;
    }

    
    @Column(name="CIUDAD", nullable=false, length=200)
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }

    
    @Column(name="CALLE", nullable=false, length=200)
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }

    
    @Column(name="NUMERO", nullable=false, precision=10, scale=0)
    public long getNumero() {
        return this.numero;
    }
    
    public void setNumero(long numero) {
        this.numero = numero;
    }

    
    @Column(name="CODIGO_POSTAL", nullable=false, length=40)
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }

    
    @Column(name="REGION", nullable=false, length=80)
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }

    
    @Column(name="LONGITUD", nullable=false, precision=12, scale=0)
    public long getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(long longitud) {
        this.longitud = longitud;
    }

    
    @Column(name="LATITUD", nullable=false, precision=12, scale=0)
    public long getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(long latitud) {
        this.latitud = latitud;
    }




}


