package entity;
// Generated 16-10-2016 1:46:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ventas generated by hbm2java
 */
@Entity
@Table(name="VENTAS"
    ,schema="GRUPO03"
)
public class Ventas  implements java.io.Serializable {


     private long idVenta;
     private Productores productores;
     private Date fechaVenta;
     private long totalVenta;
     private Set<Detallesventas> detallesventases = new HashSet<Detallesventas>(0);

    public Ventas() {
    }

	
    public Ventas(long idVenta, Date fechaVenta, long totalVenta) {
        this.idVenta = idVenta;
        this.fechaVenta = fechaVenta;
        this.totalVenta = totalVenta;
    }
    public Ventas(long idVenta, Productores productores, Date fechaVenta, long totalVenta, Set<Detallesventas> detallesventases) {
       this.idVenta = idVenta;
       this.productores = productores;
       this.fechaVenta = fechaVenta;
       this.totalVenta = totalVenta;
       this.detallesventases = detallesventases;
    }
   
     @Id 

    
    @Column(name="ID_VENTA", unique=true, nullable=false, precision=10, scale=0)
    public long getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(long idVenta) {
        this.idVenta = idVenta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRODUCTOR_PRODUCTOR_ID")
    public Productores getProductores() {
        return this.productores;
    }
    
    public void setProductores(Productores productores) {
        this.productores = productores;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_VENTA", nullable=false, length=7)
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }

    
    @Column(name="TOTAL_VENTA", nullable=false, precision=10, scale=0)
    public long getTotalVenta() {
        return this.totalVenta;
    }
    
    public void setTotalVenta(long totalVenta) {
        this.totalVenta = totalVenta;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ventas")
    public Set<Detallesventas> getDetallesventases() {
        return this.detallesventases;
    }
    
    public void setDetallesventases(Set<Detallesventas> detallesventases) {
        this.detallesventases = detallesventases;
    }




}


